'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

export default function Residents(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[building,setBuilding]=useState(''),[loading,setLoading]=useState(true),[canManage,setCanManage]=useState(false);
 async function load(){setLoading(true);const {data:user}=await supabase.auth.getUser();if(user.user){const {data:p}=await supabase.from('profiles').select('role,permissions').eq('id',user.user.id).maybeSingle();setCanManage(p?.role==='super_admin'||p?.role==='admin'||p?.role==='treasurer')}let query=supabase.from('residents').select('id,building,apartment,full_name,is_active,user_id,assigned_role').eq('is_active',true).order('building').order('apartment');if(building)query=query.eq('building',building);const {data}=await query;setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[building]);
 const filtered=rows.filter(r=>`${r.full_name||''} ${r.building||''} ${r.apartment||''}`.toLowerCase().includes(q.toLowerCase()));
 async function remove(id:string){if(!confirm('سيتم إخفاء الجار من القائمة مع الحفاظ على سجله المالي. هل تريد المتابعة؟'))return;const {error}=await supabase.from('residents').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(`تعذر حذف الجار: ${error.message}`);else load()}
 async function setRole(r:any, role:'resident'|'admin'|'super_admin'){if(!canManage)return;if(role!=='resident'&&!r.user_id){alert('يمكن حفظ صلاحيات الجار مسبقًا، لكن الدور الإداري الفعلي يحتاج إلى ربط حساب دخول. افتح إدارة الصلاحيات لإعداد ذلك.');return}if(!confirm(`تعيين ${r.full_name} بدور ${role==='super_admin'?'Super Admin':role==='admin'?'مسؤول عمارة':'جار عادي'}؟`))return;const {error:e1}=await supabase.from('residents').update({assigned_role:role,updated_at:new Date().toISOString()}).eq('id',r.id);if(e1){alert(`تعذر حفظ الدور: ${e1.message}`);return}if(r.user_id){const {error:e2}=await supabase.from('profiles').update({role}).eq('id',r.user_id);if(e2){alert(`تم حفظ تعيين الجار، لكن تعذر تحديث حساب الدخول: ${e2.message}`);return}}alert('تم تحديث الدور. ويمكن ضبط جميع الصلاحيات من زر الصلاحيات.');load()}
 return <main className="wrap"><div className="sectionTitle"><div><h2>الجيران</h2><p className="muted">إدارة الجيران وتعيين الأدوار والصلاحيات.</p></div><Link className="primary" href="/residents/new">إضافة جار</Link></div><div className="toolbar"><input placeholder="ابحث بالاسم أو العمارة أو الشقة" value={q} onChange={e=>setQ(e.target.value)}/><input placeholder="رقم العمارة" value={building} onChange={e=>setBuilding(e.target.value)}/></div>{loading?<div className="card">جاري التحميل...</div>:filtered.length===0?<div className="card empty">لا توجد بيانات تطابق البحث.</div>:<div className="card tableWrap"><table><thead><tr><th>الاسم</th><th>العمارة</th><th>الشقة</th><th>الدور</th><th>الإجراءات</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.full_name}</td><td>{r.building}</td><td>{r.apartment||'—'}</td><td>{canManage?<select value={r.assigned_role||'resident'} onChange={e=>setRole(r,e.target.value as any)}><option value="resident">جار</option><option value="admin">مسؤول عمارة</option><option value="super_admin">Super Admin</option></select>:<span className="badge">{r.assigned_role==='super_admin'?'Super Admin':r.assigned_role==='admin'?'مسؤول عمارة':'جار'}</span>}</td><td><div className="actions"><Link href={`/residents/${r.id}`}>الملف</Link>{canManage&&<Link className="secondary" href={`/admin/permissions/${r.id}`}>الصلاحيات</Link>}<Link className="secondary" href={`/residents/${r.id}/edit`}>تعديل</Link>{canManage&&<button className="danger" onClick={()=>remove(r.id)}>حذف</button>}</div></td></tr>)}</tbody></table></div>}</main>
}
