'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';
export default function Announcements(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[canManage,setCanManage]=useState(false),[permission,setPermission]=useState(typeof window!=='undefined'&&'Notification' in window?Notification.permission:'default');
 async function load(){setLoading(true);const {data}=await supabase.from('announcements').select('id,title,body,category,published,published_at,expires_at,image_url,attachment_url,attachment_name').eq('published',true).or('expires_at.is.null,expires_at.gt.'+new Date().toISOString()).order('published_at',{ascending:false});setRows(data||[]);setLoading(false)}
 async function loadRole(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();setCanManage(p?.role==='super_admin'||p?.role==='admin')}
 async function enableNotifications(){if(!('Notification' in window)){setNotice('هذا المتصفح لا يدعم إشعارات المتصفح.');return}const p=await Notification.requestPermission();setPermission(p);if(p==='granted')setNotice('تم تفعيل إشعارات الإعلانات أثناء استخدام التطبيق.')} 
 useEffect(()=>{load();loadRole();const channel=supabase.channel('announcements-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'announcements'},payload=>{const a:any=payload.new;if(a.published){setRows(r=>[a,...r]);setNotice('📢 تم نشر إعلان جديد في الحي.');if('Notification' in window&&Notification.permission==='granted')new Notification('إعلان جديد في الحي',{body:a.title})}}).subscribe();return()=>{supabase.removeChannel(channel)}},[]);
 return <main className="wrap"><div className="sectionTitle"><div><h2>إعلانات الحي</h2><p className="muted">آخر الإعلانات والمعلومات الموجهة لسكان الحي.</p></div><div className="quick"><button type="button" onClick={enableNotifications}>{permission==='granted'?'🔔 الإشعارات مفعلة':'🔔 تفعيل الإشعارات'}</button>{canManage&&<Link className="primary" href="/announcements/manage">⚙️ إدارة الإعلانات</Link>}<Link href="/">الرئيسية</Link></div></div>{notice&&<div className="notice" style={{marginBottom:14}}>{notice}</div>}{loading?<div className="card">جاري التحميل...</div>:rows.length===0?<div className="card empty">لا توجد إعلانات منشورة حاليًا.</div>:<div className="cardsGrid">{rows.map(a=><article className="card" key={a.id}>{a.image_url&&<img src={a.image_url} alt="" style={{width:'100%',maxHeight:280,objectFit:'cover',borderRadius:12,marginBottom:10}}/>}<div className="sectionTitle"><span>{a.category||'عام'}</span><small className="muted">{new Date(a.published_at).toLocaleDateString('ar-DZ')}</small></div><h3>{a.title}</h3><p style={{whiteSpace:'pre-wrap',lineHeight:1.8}}>{a.body}</p>{a.attachment_url&&<a href={a.attachment_url} target="_blank" rel="noreferrer">📎 {a.attachment_name||'فتح المرفق'}</a>}{canManage&&<div className="actions" style={{marginTop:12}}><Link className="secondary" href="/announcements/manage">✏️ تحرير الإعلانات</Link></div>}</article>)}</div>}</main>}
