'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../../lib/supabase';
const empty={title:'',body:'',category:'عام',published:true,expires_at:''};
export default function ManageAnnouncements(){
 const [f,setF]=useState(empty),[rows,setRows]=useState<any[]>([]),[edit,setEdit]=useState<string|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const {data}=await supabase.from('announcements').select('*').order('published_at',{ascending:false});setRows(data||[])} useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();setBusy(true);const payload={title:f.title,body:f.body,category:f.category,published:f.published,expires_at:f.expires_at?new Date(f.expires_at).toISOString():null,updated_at:new Date().toISOString()};const r=edit?await supabase.from('announcements').update(payload).eq('id',edit):await supabase.from('announcements').insert(payload);setMsg(r.error?`تعذر الحفظ: ${r.error.message}`:'تم حفظ الإعلان بنجاح.');if(!r.error){setF(empty);setEdit(null);load()}setBusy(false)}
 async function remove(id:string){if(!confirm('هل تريد حذف هذا الإعلان؟'))return;const {error}=await supabase.from('announcements').delete().eq('id',id);setMsg(error?`تعذر الحذف: ${error.message}`:'تم حذف الإعلان.');if(!error)load()}
 function start(a:any){setEdit(a.id);setF({title:a.title,body:a.body,category:a.category||'عام',published:a.published,expires_at:a.expires_at?a.expires_at.slice(0,16):''})}
 return <main className="wrap"><div className="sectionTitle"><div><h2>إدارة إعلانات الحي</h2><p className="muted">إضافة وتعديل وحذف ونشر الإعلانات.</p></div><Link href="/announcements">الإعلانات</Link></div><form className="card formGrid" onSubmit={save}><label>العنوان<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>التصنيف<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>عام</option><option>تنبيه</option><option>اجتماع</option><option>صيانة</option><option>مالي</option></select></label><label style={{gridColumn:'1/-1'}}>نص الإعلان<textarea required value={f.body} onChange={e=>setF({...f,body:e.target.value})}/></label><label>تاريخ انتهاء اختياري<input type="datetime-local" value={f.expires_at} onChange={e=>setF({...f,expires_at:e.target.value})}/></label><label className="consentRow"><input type="checkbox" checked={f.published} onChange={e=>setF({...f,published:e.target.checked})}/><span>منشور للسكان</span></label><div><button className="primary" disabled={busy}>{busy?'جاري الحفظ...':edit?'حفظ التعديل':'نشر الإعلان'}</button></div>{msg&&<div className="notice">{msg}</div>}</form><div className="cardsGrid">{rows.map(a=><article className="card" key={a.id}><div className="sectionTitle"><strong>{a.title}</strong><span>{a.published?'منشور':'مخفي'}</span></div><p style={{whiteSpace:'pre-wrap'}}>{a.body}</p><small className="muted">{a.category} • {new Date(a.published_at).toLocaleDateString('ar-DZ')}</small><div className="quick" style={{marginTop:12}}><button type="button" onClick={()=>start(a)}>تعديل</button><button type="button" onClick={()=>remove(a.id)}>حذف</button></div></article>)}</div></main>}
