'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {supabase} from '../../../lib/supabase';
const empty={title:'',body:'',category:'عام',published:true,expires_at:'',image_url:'',attachment_url:'',attachment_name:'',attachment_type:''};
export default function ManageAnnouncements(){
 const router=useRouter();const [ready,setReady]=useState(false),[f,setF]=useState(empty),[rows,setRows]=useState<any[]>([]),[edit,setEdit]=useState<string|null>(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[image,setImage]=useState<File|null>(null),[attachment,setAttachment]=useState<File|null>(null);
 async function checkAccess(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();if(p?.role!=='super_admin'&&p?.role!=='admin'){router.replace('/announcements');return}setReady(true);load()}
 async function load(){const {data,error}=await supabase.from('announcements').select('*').order('published_at',{ascending:false});if(error){setMsg(`تعذر تحميل الإعلانات: ${error.message}`);return}setRows(data||[])} useEffect(()=>{checkAccess()},[]);
 async function upload(file:File){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${Date.now()}-${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('announcements').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return supabase.storage.from('announcements').getPublicUrl(path).data.publicUrl}
 async function save(e:any){e.preventDefault();setBusy(true);setMsg('');try{let imageUrl=f.image_url||null,attachmentUrl=f.attachment_url||null,attachmentName=f.attachment_name||null,attachmentType=f.attachment_type||null;if(image){if(!image.type.startsWith('image/'))throw new Error('ملف الصورة غير صالح.');if(image.size>5*1024*1024)throw new Error('حجم الصورة يجب ألا يتجاوز 5 ميغابايت.');imageUrl=await upload(image)}if(attachment){if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(attachment.type))throw new Error('المرفق يجب أن يكون PDF أو صورة.');if(attachment.size>10*1024*1024)throw new Error('حجم المرفق يجب ألا يتجاوز 10 ميغابايت.');attachmentUrl=await upload(attachment);attachmentName=attachment.name;attachmentType=attachment.type}const payload={title:f.title,body:f.body,category:f.category,published:f.published,expires_at:f.expires_at?new Date(f.expires_at).toISOString():null,updated_at:new Date().toISOString(),image_url:imageUrl,attachment_url:attachmentUrl,attachment_name:attachmentName,attachment_type:attachmentType};const r=edit?await supabase.from('announcements').update(payload).eq('id',edit):await supabase.from('announcements').insert(payload);if(r.error)throw r.error;setMsg('تم حفظ الإعلان بنجاح.');setF(empty);setImage(null);setAttachment(null);setEdit(null);load()}catch(err:any){setMsg(`تعذر الحفظ: ${err.message}`)}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('هل تريد حذف هذا الإعلان؟'))return;const {error}=await supabase.from('announcements').delete().eq('id',id);setMsg(error?`تعذر الحذف: ${error.message}`:'تم حذف الإعلان.');if(!error)load()}
 function start(a:any){setEdit(a.id);setF({title:a.title,body:a.body,category:a.category||'عام',published:a.published,expires_at:a.expires_at?a.expires_at.slice(0,16):'',image_url:a.image_url||'',attachment_url:a.attachment_url||'',attachment_name:a.attachment_name||'',attachment_type:a.attachment_type||''});setImage(null);setAttachment(null);window.scrollTo({top:0,behavior:'smooth'})}
 if(!ready)return <main className="authScreen"><div className="card authCard">جاري التحقق من صلاحية الإدارة...</div></main>;
 return <main className="wrap"><div className="sectionTitle"><div><h2>إدارة إعلانات الحي</h2><p className="muted">إضافة وتعديل وحذف ونشر الإعلانات مع الصور وملفات PDF.</p></div><div className="actions"><Link href="/announcements">الإعلانات</Link><button type="button" onClick={()=>{setEdit(null);setF(empty);setImage(null);setAttachment(null)}}>➕ إعلان جديد</button></div></div><form className="card formGrid" onSubmit={save}><label>العنوان<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>التصنيف<select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>عام</option><option>تنبيه</option><option>اجتماع</option><option>صيانة</option><option>مالي</option></select></label><label style={{gridColumn:'1/-1'}}>نص الإعلان<textarea required value={f.body} onChange={e=>setF({...f,body:e.target.value})}/></label><label>تاريخ انتهاء اختياري<input type="datetime-local" value={f.expires_at} onChange={e=>setF({...f,expires_at:e.target.value})}/></label><label className="consentRow"><input type="checkbox" checked={f.published} onChange={e=>setF({...f,published:e.target.checked})}/><span>منشور للسكان</span></label><label>صورة الإعلان<input type="file" accept="image/*" onChange={e=>setImage(e.target.files?.[0]||null)}/></label><label>PDF أو صورة مرفقة<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setAttachment(e.target.files?.[0]||null)}/></label><div><button className="primary" disabled={busy}>{busy?'جاري الحفظ...':edit?'حفظ التعديل':'نشر الإعلان'}</button></div>{msg&&<div className="notice">{msg}</div>}</form><div className="cardsGrid">{rows.map(a=><article className="card" key={a.id}>{a.image_url&&<img src={a.image_url} alt="" style={{width:'100%',maxHeight:220,objectFit:'cover',borderRadius:12,marginBottom:10}}/>}<div className="sectionTitle"><strong>{a.title}</strong><span>{a.published?'منشور':'مخفي'}</span></div><p style={{whiteSpace:'pre-wrap'}}>{a.body}</p><small className="muted">{a.category} • {new Date(a.published_at).toLocaleDateString('ar-DZ')}</small>{a.attachment_url&&<p><a href={a.attachment_url} target="_blank" rel="noreferrer">📎 {a.attachment_name||'فتح المرفق'}</a></p>}<div className="quick" style={{marginTop:12}}><button type="button" onClick={()=>start(a)}>✏️ تعديل</button><button type="button" onClick={()=>remove(a.id)}>🗑️ حذف</button></div></article>)}</div></main>}
