'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';

export default function TreasuryPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(''); const [t,setT]=useState<any>(null); const [cs,setCs]=useState<any[]>([]); const [es,setEs]=useState<any[]>([]); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{params.then(p=>setId(p.id))},[params]);
 async function load(){if(!id)return;setLoading(true);const [{data:t0},{data:cs0},{data:es0}]=await Promise.all([supabase.from('treasury_summary').select('*').eq('id',id).single(),supabase.from('contributions').select('id,amount,contribution_date,resident_id,residents(full_name,building,apartment)').eq('treasury_id',id).order('contribution_date',{ascending:false}),supabase.from('transactions').select('id,amount,transaction_date,title,description').eq('treasury_id',id).eq('kind','expense').order('transaction_date',{ascending:false})]);setT(t0);setCs(cs0||[]);setEs(es0||[]);setLoading(false)}
 useEffect(()=>{load()},[id]);
 async function remove(){if(!confirm('سيتم إخفاء الخزينة من القوائم مع الحفاظ على سجلها المالي. هل تريد المتابعة؟'))return;const {error}=await supabase.rpc('soft_delete_treasury',{treasury_id:id});setMsg(error?`تعذر حذف الخزينة: ${error.message}`:'تم حذف الخزينة من القوائم مع الحفاظ على سجلها المالي.');if(!error)setTimeout(()=>{window.location.href='/treasuries'},700)}
 if(loading)return <main className="wrap"><div className="card">جاري التحميل...</div></main>;
 if(!t)return <main className="wrap"><div className="card empty">الخزينة غير موجودة.</div></main>;
 return <main className="wrap"><div className="sectionTitle"><div><h2>{t.name}</h2><p className="muted">{t.purpose||t.description||'—'}</p></div><div className="actions"><Link className="secondary" href={`/treasuries/${id}/edit`}>تعديل</Link><button className="danger" onClick={remove}>حذف</button></div></div>{msg&&<div className="notice">{msg}</div>}<section className="stats"><div className="card"><div className="statLabel">المستهدف</div><div className="statValue">{Number(t.target_amount).toLocaleString('ar-DZ')} دج</div></div><div className="card"><div className="statLabel">المحصل</div><div className="statValue">{Number(t.total_contributions).toLocaleString('ar-DZ')} دج</div></div><div className="card"><div className="statLabel">المصروف</div><div className="statValue">{Number(t.total_expenses).toLocaleString('ar-DZ')} دج</div></div><div className="card"><div className="statLabel">الرصيد الحالي</div><div className="statValue">{Number(t.balance).toLocaleString('ar-DZ')} دج</div></div></section><div className="card"><h3>نسبة تحقيق الهدف: {Number(t.target_percent)||0}%</h3><div className="progress"><div style={{width:`${Math.min(100,Number(t.target_percent)||0)}%`}}/></div></div><div className="grid"><div className="card"><h3>المساهمون</h3>{!cs.length?<div className="empty">لا توجد مساهمات.</div>:cs.map(c=><div className="tx" key={c.id}><div>{c.residents?.full_name||'جار'} — عمارة {c.residents?.building||'—'} شقة {c.residents?.apartment||'—'}<div className="txSub">{c.contribution_date}</div></div><b className="green">+{Number(c.amount).toLocaleString('ar-DZ')} دج</b></div>)}</div><div className="card"><h3>المصاريف</h3>{!es.length?<div className="empty">لا توجد مصاريف.</div>:es.map(e=><div className="tx" key={e.id}><div>{e.title}<div className="txSub">{e.transaction_date} {e.description?'• '+e.description:''}</div></div><b className="red">−{Number(e.amount).toLocaleString('ar-DZ')} دج</b></div>)}</div></div></main>
}