'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { supabase } from '../../../../lib/supabase';

type Permission = { key: string; label: string };
type Group = { title: string; items: Permission[] };

const GROUPS: Group[] = [
  { title: '👤 الحساب والملف الشخصي', items: [{key:'profile.view',label:'مشاهدة ملفه الشخصي'},{key:'profile.update',label:'تعديل بياناته الشخصية'},{key:'profile.password',label:'تغيير كلمة المرور'}] },
  { title: '👥 السكان والجيران', items: [{key:'residents.view_building',label:'مشاهدة قائمة سكان العمارة'},{key:'residents.view_contact',label:'مشاهدة بيانات الاتصال للسكان'},{key:'residents.create',label:'إضافة جار'},{key:'residents.update',label:'تعديل بيانات جار'},{key:'residents.delete',label:'حذف جار'},{key:'residents.disable',label:'تعطيل حساب جار'},{key:'residents.reactivate',label:'إعادة تفعيل حساب جار'}] },
  { title: '🏢 العمارات', items: [{key:'buildings.view',label:'مشاهدة بيانات العمارة'},{key:'buildings.update',label:'تعديل بيانات العمارة'},{key:'buildings.create',label:'إضافة عمارة'},{key:'buildings.delete',label:'حذف عمارة'},{key:'buildings.assign_admin',label:'تعيين مسؤول عمارة'},{key:'buildings.change_admin',label:'تغيير مسؤول العمارة'}] },
  { title: '📢 الإعلانات', items: [{key:'announcements.view',label:'مشاهدة الإعلانات'},{key:'announcements.create',label:'إنشاء إعلان'},{key:'announcements.update_own',label:'تعديل إعلانه'},{key:'announcements.update_all',label:'تعديل إعلانات الآخرين'},{key:'announcements.delete_own',label:'حذف إعلانه'},{key:'announcements.delete_all',label:'حذف إعلانات الآخرين'},{key:'announcements.pin',label:'تثبيت إعلان'},{key:'announcements.publish_all',label:'نشر إعلان لجميع الحي'},{key:'announcements.publish_building',label:'نشر إعلان لعمارة محددة'}] },
  { title: '📣 الشكاوى والبلاغات', items: [{key:'complaints.create',label:'إنشاء شكوى أو بلاغ'},{key:'complaints.view_own',label:'مشاهدة شكواه'},{key:'complaints.view_building',label:'مشاهدة شكاوى سكان العمارة'},{key:'complaints.reply',label:'الرد على الشكاوى'},{key:'complaints.status',label:'تغيير حالة الشكوى'},{key:'complaints.delete',label:'حذف شكوى'},{key:'complaints.view_all',label:'مشاهدة جميع شكاوى الحي'}] },
  { title: '💰 المساهمات والمصاريف', items: [{key:'finance.view',label:'مشاهدة المساهمات'},{key:'contributions.create',label:'تسجيل مساهمة'},{key:'contributions.update',label:'تعديل مساهمة'},{key:'contributions.delete',label:'حذف مساهمة'},{key:'expenses.view_building',label:'مشاهدة مصاريف العمارة'},{key:'expenses.create',label:'تسجيل مصروف'},{key:'expenses.update',label:'تعديل مصروف'},{key:'expenses.delete',label:'حذف مصروف'},{key:'finance.view_all',label:'مشاهدة مالية كامل الحي'}] },
  { title: '📄 الوثائق والملفات', items: [{key:'documents.view',label:'مشاهدة وثائق العمارة'},{key:'documents.upload',label:'رفع وثيقة'},{key:'documents.delete',label:'حذف وثيقة'},{key:'documents.download',label:'تحميل الوثائق'}] },
  { title: '🗓️ المواعيد والاجتماعات', items: [{key:'appointments.view',label:'مشاهدة المواعيد'},{key:'appointments.create',label:'إنشاء موعد'},{key:'appointments.update',label:'تعديل موعد'},{key:'appointments.delete',label:'حذف موعد'},{key:'meetings.create_building',label:'إنشاء اجتماع سكان العمارة'}] },
  { title: '🏠 إدارة العمارة', items: [{key:'building.manage',label:'إدارة معلومات العمارة'},{key:'building.facilities',label:'إدارة مرافق العمارة'},{key:'building.issue.create',label:'تسجيل مشكلة في العمارة'},{key:'building.issue.manage',label:'متابعة مشاكل العمارة'},{key:'building.notify',label:'إرسال تنبيه لسكان العمارة'}] },
  { title: '📊 التقارير والإحصائيات', items: [{key:'reports.building',label:'مشاهدة إحصائيات العمارة'},{key:'reports.finance_building',label:'مشاهدة التقارير المالية للعمارة'},{key:'reports.all',label:'مشاهدة إحصائيات الحي'},{key:'reports.export',label:'تصدير البيانات'}] },
  { title: '⚙️ إدارة المستخدمين', items: [{key:'users.view',label:'مشاهدة المستخدمين'},{key:'users.create',label:'إنشاء حساب مستخدم'},{key:'users.update',label:'تعديل حساب مستخدم'},{key:'users.disable',label:'تعطيل حساب مستخدم'},{key:'users.delete',label:'حذف حساب مستخدم'},{key:'users.role',label:'تغيير دور المستخدم'},{key:'users.permissions',label:'تغيير صلاحيات المستخدم'},{key:'users.assign_building_admin',label:'تعيين مسؤول عمارة'}] },
  { title: '🔐 إدارة النظام', items: [{key:'system.settings',label:'إدارة إعدادات التطبيق'},{key:'system.buildings',label:'إدارة العمارات'},{key:'system.permissions',label:'إدارة الصلاحيات'},{key:'system.audit',label:'مشاهدة سجل العمليات'},{key:'system.backups',label:'إدارة النسخ الاحتياطية'}] },
];
const ALL_KEYS = GROUPS.flatMap(g => g.items.map(x => x.key));

export default function PermissionEditor(){
  const params = useParams<{residentId:string}>(); const router = useRouter();
  const [resident,setResident]=useState<any>(null); const [role,setRole]=useState<'resident'|'admin'|'super_admin'>('resident'); const [building,setBuilding]=useState(''); const [permissions,setPermissions]=useState<Record<string,boolean>>({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const enabledCount = useMemo(()=>ALL_KEYS.filter(k=>permissions[k]).length,[permissions]);
  useEffect(()=>{(async()=>{ const {data:user}=await supabase.auth.getUser(); if(!user.user){router.replace('/login');return;} const {data:profile}=await supabase.from('profiles').select('role').eq('id',user.user.id).maybeSingle(); if(profile?.role!=='super_admin'){router.replace('/');return;} const {data,error:e}=await supabase.from('residents').select('id,full_name,phone,building,apartment,user_id,assigned_role,permissions,building_scope').eq('id',params.residentId).maybeSingle(); if(e||!data){setError('تعذر العثور على الجار.');setLoading(false);return;} setResident(data);setRole(data.assigned_role||'resident');setBuilding(data.building_scope||data.building||'');setPermissions(data.permissions||{}); if(data.user_id){const {data:p}=await supabase.from('profiles').select('role,permissions,building_scope').eq('id',data.user_id).maybeSingle();if(p){setRole(p.role||data.assigned_role||'resident');setPermissions(p.permissions||data.permissions||{});setBuilding(p.building_scope||data.building_scope||data.building||'')}} setLoading(false); })()},[params.residentId,router]);
  function setAll(value:boolean){setPermissions(Object.fromEntries(ALL_KEYS.map(k=>[k,value])))}
  function toggle(key:string){setPermissions(p=>({...p,[key]:!p[key]}))}
  async function save(){setSaving(true);setError('');const {error:e}=await supabase.rpc('set_resident_permissions',{target_resident_id:params.residentId,new_role:role,new_permissions:permissions,target_building:building});if(e){setError(e.message);setSaving(false);return}alert('تم حفظ الدور والصلاحيات بنجاح.');router.push('/residents')}
  if(loading)return <main className="wrap"><div className="card">جاري تحميل الصلاحيات...</div></main>;
  if(!resident)return <main className="wrap"><div className="card notice">{error||'الجار غير موجود.'}</div></main>;
  return <main className="wrap"><div className="sectionTitle"><div><h2>إدارة الصلاحيات</h2><p className="muted">{resident.full_name} — العمارة {resident.building} — الشقة {resident.apartment||'—'}</p></div><Link href="/residents">العودة للجيران</Link></div>{error&&<div className="notice" style={{marginBottom:14}}>{error}</div>}
    <section className="card" style={{marginBottom:14}}><div className="formGrid"><label>الدور الأساسي<select value={role} onChange={e=>setRole(e.target.value as any)}><option value="resident">جار عادي</option><option value="admin">مسؤول عمارة (Admin)</option><option value="super_admin">Super Admin</option></select></label><label>نطاق العمارة<input value={building} onChange={e=>setBuilding(e.target.value)} placeholder="مثال: 12" /></label></div><div className="sectionTitle"><strong>الصلاحيات المخصصة</strong><span className="muted">{enabledCount} / {ALL_KEYS.length} مفعلة</span></div><div className="quick"><button className="primary" type="button" onClick={()=>setAll(true)}>تفعيل الكل</button><button type="button" onClick={()=>setAll(false)}>شطب الكل</button></div></section>
    {GROUPS.map(g=>{const all=g.items.every(i=>permissions[i.key]);return <section className="card" key={g.title} style={{marginBottom:14}}><div className="sectionTitle"><h3>{g.title}</h3><button type="button" onClick={()=>setPermissions(p=>({...p,...Object.fromEntries(g.items.map(i=>[i.key,!all]))}))}>{all?'شطب المجموعة':'تفعيل المجموعة'}</button></div><div className="permissionGrid">{g.items.map(item=><label className="permissionItem" key={item.key}><input type="checkbox" checked={!!permissions[item.key]} onChange={()=>toggle(item.key)}/><span>{item.label}</span></label>)}</div></section>})}
    <div className="card" style={{position:'sticky',bottom:10}}><button className="primary" type="button" disabled={saving} onClick={save}>{saving?'جاري الحفظ...':'حفظ الدور والصلاحيات'}</button></div></main>;
}
